### PR TITLE
Mouse release event: once mleftbutton is released, stop capturing

### PR DESCRIPTION
**Pull request by asamy**
Standard in screenshot capturing tools :P

P.S.: Are you working on a global hotkey handler or should I create an issue and work on it?

### CODE REVIEW

**Comment by veeti** [comment]
Thanks for the PR. I'd like to have this available as a (non-default) setting, as I plan to add some non-instant cropping features sooner or later (see #11 and #12).

I've personally set a global hotkey through my desktop environment and I think most WM's/DE's support doing so, so I don't think that built-in support is necessary. From a quick look I had earlier it also seems like Qt doesn't support global hotkeys, so doing so would require some ugly Xlib code I'd rather avoid.

**Comment by asamy** [comment]
That sounds like a good idea, but sticking to non-default is probably a bad idea to most users, that is because most screenshot tools out there use it as a default setting, however, to simplify user-sided stuff I'd do some `QWizard` widgets that help the user get started.  What do you think?

**Comment by veeti** [comment]
I don't think that there's nearly enough settings to justify a wizard sort of thing right now. I really want this to be an install-and-go type of program.

How about I merge this now and think about making it a setting if and once I get to adding new features? You'll have to update the `mHelpLabel` text, remove the "click inside cropper" code since it's now pointless and while you're at it change the commit message to something simpler like "crop instantly after mouse release".

**Comment by asamy** [comment]
Sorry for the late response.  I've updated my commit

**Comment by asamy** [comment]
No problem.

**Pull request merged**
